# Generated by Django 3.2 on 2023-09-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_theme',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
