# Generated by Django 3.2 on 2023-10-10 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=32)),
                ('status', models.CharField(default='On Route', max_length=32)),
                ('location', models.CharField(default='Mockville, MO', max_length=32)),
                ('estimated_delivery', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackingOrder', to='checkout.order')),
            ],
        ),
    ]
