# Generated by Django 3.2 on 2023-10-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_trackingorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingorder',
            name='tracking_number',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
