# Generated by Django 3.2 on 2023-09-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230919_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='universe',
        ),
    ]
