# Generated by Django 3.2 on 2023-09-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230919_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='universe',
            field=models.CharField(default='real', max_length=254),
        ),
    ]
